name: 573a3386 

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - run: |
           gh issue list
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
